### ISSUE TITLE
hover uitschakelen op niet-cursor apparaat

### ISSUE THREAD

**Issue by julia-stevens** [julia-stevens/fix-the-flow-interactive-website#36]
Hover effecten zijn nu nog actief op mobiel, dit moet uitgeschakeld worden

Bronnen: 
* https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer#coarse
* https://developer.mozilla.org/en-US/docs/Web/CSS/all#revert-layer

**Comment by julia-stevens** [comment]
**Voorbeeld**

```css
/* set link hover styles as normal */

a:hover {
  color: red;
  text-decoration: underline wavy;
  /* etc. > ignore all at once for touch devices */
}


/* revert all link hover declarations for touch devices */

@media (pointer: coarse) {
  a:hover {
    all: revert-layer;
  }
}
```
